# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 358af0598eed52bf723901f4058c0421f87d93bbd470e8be8e391beb17d57c7a1ad0809e88082c1cfb12f3b0b4868e8c276f2dff5ab3c9fd6d0ae04c527a68b5

test:
  secret_key_base: a6e9e92ee1c4644b4242344de0544e1cbcd71be77666596e3ce025170b2168817e7ed733870d80c8822820007dacdae7ceb2d770a519b7238b9fa0f8fa12ef87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
